

mod_id=letthemgrow
curse_id=368534
curse_slug=let-them-grow
mod_version=1.1.0
mod_name=letthemgrow
mod_group_id=com.lothrazar.letthemgrow
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=

flib_version=0.2.8
flib_file=8482026


