#General settings
[letthemgrow]
	#If true, then when a cow is milked too often it becomes un-milkable for a time
	limitedMilk = false
	#Once every tick, this is the percentage chance that growth will be blocked; so 99 is very slow, and 1 is fast.
	# Default: 0
	# Range: 0 ~ 100
	saplingSlowdownChance = 0
	#Once every tick, this is the percentage chance that growth will be blocked; so 99 is very slow, and 1 is fast.
	# Default: 0
	# Range: 0 ~ 100
	cropsSlowdownChance = 0
	#Once every tick, this is the percentage chance that growth will be blocked; so 99 is very slow, and 1 is fast.
	# Default: 0
	# Range: 0 ~ 100
	livestockSlowdownChance = 0
	#True to disable feeding any compatible items to child animals
	blockFeedingYoung = true
